pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "Android-Security-Masterclass"
include(":app-vulnerable")
include(":app-secure")
include(":app-attacker")   // Malicious third-party app for IPC exploit demonstrations
include(":common")
include(":features:maswe0001")
include(":features:maswe0002")
include(":features:maswe0003")
include(":features:maswe0004")
include(":features:maswe0005")
include(":features:maswe0006")
include(":features:maswe0007")
include(":features:maswe0008")
include(":features:maswe0009")
include(":features:maswe0010")
include(":features:maswe0011")
include(":features:maswe0012")
include(":features:maswe0013")
include(":features:maswe0014")
include(":features:maswe0015")
include(":features:maswe0016")
include(":features:maswe0017")
include(":features:maswe0018")
include(":features:maswe0019")
include(":features:maswe0020")
include(":features:maswe0021")
include(":features:maswe0022")
include(":features:maswe0023")
include(":features:maswe0024")
include(":features:maswe0025")
include(":features:maswe0026")
include(":features:maswe0027")
include(":features:maswe0028")
include(":features:maswe0029")
include(":features:maswe0030")
include(":features:maswe0031")
include(":features:maswe0032")
include(":features:maswe0033")
include(":features:maswe0034")
include(":features:maswe0035")
include(":features:maswe0036")
include(":features:maswe0037")
include(":features:maswe0038")
include(":features:maswe0039")
include(":features:maswe0040")
include(":features:maswe0041")
include(":features:maswe0042")
include(":features:maswe0043")
include(":features:maswe0044")
include(":features:maswe0045")
include(":features:maswe0046")
include(":features:maswe0047")
include(":features:maswe0048")
include(":features:maswe0049")
include(":features:maswe0050")
include(":features:maswe0051")
include(":features:maswe0052")
include(":features:maswe0053")
include(":features:maswe0054")
include(":features:maswe0055")
include(":features:maswe0056")
include(":features:maswe0057")
include(":features:maswe0058")
include(":features:maswe0059")
include(":features:maswe0060")
include(":features:maswe0061")
include(":features:maswe0062")
include(":features:maswe0063")
include(":features:maswe0064")
include(":features:maswe0065")
include(":features:maswe0066")
include(":features:maswe0067")
include(":features:maswe0068")
include(":features:maswe0069")
include(":features:maswe0070")
include(":features:maswe0071")
include(":features:maswe0072")
include(":features:maswe0073")
include(":features:maswe0074")
include(":features:maswe0075")
include(":features:maswe0076")
include(":features:maswe0077")
include(":features:maswe0078")